name: TemplatePlugin
version: ${project.version}
main: me.giodev.templateplugin.TemplatePlugin
api-version: 1.16
commands:
  tpcommand:
    aliases: ["tpcmd"]
    usage: "/tpcommand <args>"
    description: "Template command"