name: TemplatePlugin
version: ${project.version}
main: me.giodev.templateplugin.TemplatePlugin
api-version: 1.16
commands:
  excommand:
    aliases: ["excmd"]
    usage: "/tpcommand <args>"
    description: "Example command"